# Workflow for the scraping iteration A process

# Whenever pull request is made targeting branch initialisation, csv is reset
name: iteration-A

# Workflow's description
run-name: Scrape the products in daily errors and store raw data 

# Function to schedule the minutes, hour (UTC time), day of month (*), month (*), and day of week (*) of the workflow process
on:
  schedule:
    - cron: '01 14 * * 1-5' #UTC time and weekday (0=Sunday, 1=Monday,..., 6=Saturday)
  #workflow_dispatch: # Allows manual testing
  
#on:
#  pull_request:
#    # Sequence of patterns matched against refs/heads
#    branches:
#      - iteration-A 

jobs:
  getdataandrefreshmap:
    runs-on: ubuntu-latest
    
    steps:
      # It checks out the latest content of your repository
      - name: Checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
        with:
          fetch-depth: 0
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11 #install the python needed
      
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      
      # Installs the required Python dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements-2.txt ]; then pip install --no-cache-dir -r requirements-2.txt; fi
      
      - name: Run IterationA.py
        run: |
          python ECOICOPv2/PythonCodes/IterationA.py
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "scraping iteration A completed"
          git push origin HEAD:main
